### ISSUE TITLE
I am looking forward to your released code.

### ISSUE THREAD

**Issue by Magicboomliu** [Yizhou-Li-CV/DPRRN#1]
Hi, Thank you for your outstanding work. 
Have you trying using your model to do stereo matching task at rainy days at public stereo dataset like SceneFlow and KITTI.
If you are insterested in it, I am glad to seek for a corporation.

**Comment by Yizhou-Li-CV** [comment]
Thank you very much for your comments. I welcome and you may further contact me with my email.

**Comment by Magicboomliu** [comment]
您好，邮件已收到。感谢来信 ，我会尽快回复您。  Hello, I have already received the letter. Thanks for your mailing, I will reply as soon as possible.  こんにちは！確かご電子メールをもらいました。私はできるだけ早くあなたに返事を出します。

**Comment by Magicboomliu** [comment]
您好，邮件已收到。感谢来信 ，我会尽快回复您。  Hello, I have already received the letter. Thanks for your mailing, I will reply as soon as possible.  こんにちは！確かご電子メールをもらいました。私はできるだけ早くあなたに返事を出します。
