### ISSUE TITLE
The code of data rendering

### ISSUE THREAD

**Issue by stalin18** [Yizhou-Li-CV/DPRRN#2]
Hi! Will you be making the code of data rendering available?

**Comment by Yizhou-Li-CV** [comment]
Thank you very much for the comments. Yes, we are currently extending our work and plan to release the code of the data rendering after we finish the extension.

**Comment by stalin18** [comment]
Hello @Yizhou-Li-CV , regarding the rendering code, could you please clarify if you had to perform the blur kernel calibration or using the already provided calibration data here (https://imaging.cs.cmu.edu/dual_pixels/) worked?

**Comment by Yizhou-Li-CV** [comment]
Hello, we use the already provided calibrated kernels for rendering as you mentioned: https://imaging.cs.cmu.edu/dual_pixels/

**Comment by Yukarizz** [comment]
hello，i also need the code of raindrop rendering. i will be appreciate if you could share the rendering code. Thank you very much.

**Comment by Yizhou-Li-CV** [comment]
Sorry for the delayed response. I've been quite busy lately. 
I’ve updated the code for raindrop rendering. Feel free to reach out if there are any further questions.
