### ISSUE TITLE
The resolution of images in the dataset

### ISSUE THREAD

**Issue by stalin18** [Yizhou-Li-CV/DPRRN#3]
Hello! I downloaded your shared dataset, I see that the images in your dataset have the resolution 528x400 or 528x396. 
However, the Pixel 4 smartphone captures images of resolution 2016x1512. Could you please explain how and why did you obtain 528x400 or 528x396 images in your dataset?

**Comment by Yizhou-Li-CV** [comment]
Thank you for your attention. We indeed capture the image with resolution 2016x1512. But for efficiency during training and test, we downsample image using linear interpolation into smaller size.
